//! Built-in policy presets.

use super::{PolicyRule, PolicySet};

/// Get a built-in preset by name.
pub fn get_preset(name: &str) -> Option<PolicySet> {
    match name {
        "basic-hygiene" => Some(basic_hygiene()),
        "production-ready" => Some(production_ready()),
        "security-focused" => Some(security_focused()),
        _ => None,
    }
}

/// List all available preset names.
pub fn list_presets() -> Vec<&'static str> {
    vec!["basic-hygiene", "production-ready", "security-focused"]
}

fn basic_hygiene() -> PolicySet {
    PolicySet {
        id: "basic-hygiene".into(),
        name: "Basic Hygiene".into(),
        description: "Minimum standards for a well-maintained repository".into(),
        rules: vec![
            PolicyRule {
                id: "bh-overall".into(),
                name: "Overall score >= 40".into(),
                description: "Repository must score at least 40 overall".into(),
                rule_type: "overall-score".into(),
                operator: ">=".into(),
                value: 40.0,
                category: String::new(),
                signal: String::new(),
                severity: "error".into(),
            },
            PolicyRule {
                id: "bh-readme".into(),
                name: "README exists".into(),
                description: "Repository must have a README".into(),
                rule_type: "signal".into(),
                operator: "exists".into(),
                value: 0.0,
                category: String::new(),
                signal: "README exists".into(),
                severity: "error".into(),
            },
            PolicyRule {
                id: "bh-license".into(),
                name: "License file exists".into(),
                description: "Repository must have a LICENSE file".into(),
                rule_type: "signal".into(),
                operator: "exists".into(),
                value: 0.0,
                category: String::new(),
                signal: "License file exists".into(),
                severity: "warning".into(),
            },
            PolicyRule {
                id: "bh-gitignore".into(),
                name: ".gitignore present".into(),
                description: "Repository should have a .gitignore".into(),
                rule_type: "signal".into(),
                operator: "exists".into(),
                value: 0.0,
                category: String::new(),
                signal: ".gitignore present".into(),
                severity: "warning".into(),
            },
            PolicyRule {
                id: "bh-deps".into(),
                name: "Dependency manifest".into(),
                description: "Repository should declare its dependencies".into(),
                rule_type: "signal".into(),
                operator: "exists".into(),
                value: 0.0,
                category: String::new(),
                signal: "Dependency manifest".into(),
                severity: "info".into(),
            },
        ],
    }
}

fn production_ready() -> PolicySet {
    PolicySet {
        id: "production-ready".into(),
        name: "Production Ready".into(),
        description: "Standards for production-grade repositories".into(),
        rules: vec![
            PolicyRule {
                id: "pr-overall".into(),
                name: "Overall score >= 70".into(),
                description: "Repository must score at least 70 overall".into(),
                rule_type: "overall-score".into(),
                operator: ">=".into(),
                value: 70.0,
                category: String::new(),
                signal: String::new(),
                severity: "error".into(),
            },
            PolicyRule {
                id: "pr-cicd".into(),
                name: "CI/CD >= 60".into(),
                description: "CI/CD score must be at least 60".into(),
                rule_type: "category-score".into(),
                operator: ">=".into(),
                value: 60.0,
                category: "cicd".into(),
                signal: String::new(),
                severity: "error".into(),
            },
            PolicyRule {
                id: "pr-security".into(),
                name: "Security >= 50".into(),
                description: "Security score must be at least 50".into(),
                rule_type: "category-score".into(),
                operator: ">=".into(),
                value: 50.0,
                category: "security".into(),
                signal: String::new(),
                severity: "error".into(),
            },
            PolicyRule {
                id: "pr-quality".into(),
                name: "Code Quality >= 50".into(),
                description: "Code quality score must be at least 50".into(),
                rule_type: "category-score".into(),
                operator: ">=".into(),
                value: 50.0,
                category: "code_quality".into(),
                signal: String::new(),
                severity: "error".into(),
            },
            PolicyRule {
                id: "pr-tests".into(),
                name: "Tests present".into(),
                description: "Repository must have tests".into(),
                rule_type: "signal".into(),
                operator: "exists".into(),
                value: 0.0,
                category: String::new(),
                signal: "Tests present".into(),
                severity: "error".into(),
            },
            PolicyRule {
                id: "pr-ci-tests".into(),
                name: "CI runs tests".into(),
                description: "CI should run tests".into(),
                rule_type: "signal".into(),
                operator: "exists".into(),
                value: 0.0,
                category: String::new(),
                signal: "CI runs tests".into(),
                severity: "warning".into(),
            },
            PolicyRule {
                id: "pr-lockfile".into(),
                name: "Lockfile present".into(),
                description: "Dependencies should be locked".into(),
                rule_type: "signal".into(),
                operator: "exists".into(),
                value: 0.0,
                category: String::new(),
                signal: "Lockfile present".into(),
                severity: "warning".into(),
            },
            PolicyRule {
                id: "pr-license".into(),
                name: "License file exists".into(),
                description: "Repository must have a LICENSE".into(),
                rule_type: "signal".into(),
                operator: "exists".into(),
                value: 0.0,
                category: String::new(),
                signal: "License file exists".into(),
                severity: "error".into(),
            },
        ],
    }
}

fn security_focused() -> PolicySet {
    PolicySet {
        id: "security-focused".into(),
        name: "Security Focused".into(),
        description: "Strict security and supply chain requirements".into(),
        rules: vec![
            PolicyRule {
                id: "sf-security".into(),
                name: "Security >= 70".into(),
                description: "Security score must be at least 70".into(),
                rule_type: "category-score".into(),
                operator: ">=".into(),
                value: 70.0,
                category: "security".into(),
                signal: String::new(),
                severity: "error".into(),
            },
            PolicyRule {
                id: "sf-openssf".into(),
                name: "OpenSSF >= 60".into(),
                description: "OpenSSF score must be at least 60".into(),
                rule_type: "category-score".into(),
                operator: ">=".into(),
                value: 60.0,
                category: "openssf".into(),
                signal: String::new(),
                severity: "error".into(),
            },
            PolicyRule {
                id: "sf-security-md".into(),
                name: "SECURITY.md".into(),
                description: "Must have a security policy".into(),
                rule_type: "signal".into(),
                operator: "exists".into(),
                value: 0.0,
                category: String::new(),
                signal: "SECURITY.md".into(),
                severity: "error".into(),
            },
            PolicyRule {
                id: "sf-dependabot".into(),
                name: "Dependabot configured".into(),
                description: "Must have dependency update automation".into(),
                rule_type: "signal".into(),
                operator: "exists".into(),
                value: 0.0,
                category: String::new(),
                signal: "Dependabot configured".into(),
                severity: "error".into(),
            },
            PolicyRule {
                id: "sf-no-secrets".into(),
                name: "No exposed secret files".into(),
                description: "Must not expose secret files".into(),
                rule_type: "signal".into(),
                operator: "exists".into(),
                value: 0.0,
                category: String::new(),
                signal: "No exposed secret files".into(),
                severity: "error".into(),
            },
            PolicyRule {
                id: "sf-no-binaries".into(),
                name: "No binary artifacts".into(),
                description: "Should not contain binary artifacts".into(),
                rule_type: "signal".into(),
                operator: "exists".into(),
                value: 0.0,
                category: String::new(),
                signal: "No binary artifacts".into(),
                severity: "warning".into(),
            },
            PolicyRule {
                id: "sf-permissions".into(),
                name: "Token permissions".into(),
                description: "Workflows should declare token permissions".into(),
                rule_type: "signal".into(),
                operator: "exists".into(),
                value: 0.0,
                category: String::new(),
                signal: "Token permissions".into(),
                severity: "warning".into(),
            },
            PolicyRule {
                id: "sf-no-dangerous".into(),
                name: "No dangerous workflow patterns".into(),
                description: "Must not use dangerous workflow patterns".into(),
                rule_type: "signal".into(),
                operator: "exists".into(),
                value: 0.0,
                category: String::new(),
                signal: "No dangerous workflow patterns".into(),
                severity: "error".into(),
            },
        ],
    }
}
