[package]
name = "repoanalyze"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "repoanalyze"
path = "src/main.rs"

[dependencies]
anyhow = "1"
thiserror = "2"
clap = { version = "4", features = ["derive", "env"] }
gix = { version = "0.80", default-features = false, features = ["blocking-network-client", "blocking-http-transport-reqwest-rust-tls", "revparse-regex"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
byteorder = "1"
crossbeam-channel = "0.5"
rayon = "1"
hashbrown = "0.15"
smallvec = "1"
bytes = "1"
imara-diff = "0.1"
regex = "1"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
tonic = "0.12"
prost = "0.14"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tower = "0.5"
dirs-next = "2.0.0"
indicatif = "0.18.4"

[build-dependencies]
tonic-build = { version = "0.12", features = ["prost"] }
protobuf-src = "2"

[dev-dependencies]
tempfile = "3"
assert_cmd = "2"
predicates = "3"
blake3 = "1"
