use std::path::Path;

use crate::techdetect::types::TechDetectResult;

/// Embedded CSS for the tech report.
const TECH_STYLE_CSS: &[u8] = include_bytes!("../../assets/tech_report.css");

/// Embedded JS for the tech report.
const TECH_APP_JS: &[u8] = include_bytes!("../../assets/tech_report.js");

/// Generate a self-contained tech-detect HTML report.
pub fn generate_tech_report(
    out_path: &Path,
    result: &TechDetectResult,
) -> anyhow::Result<()> {
    std::fs::create_dir_all(out_path.parent().unwrap_or(Path::new(".")))?;

    let style_css = String::from_utf8_lossy(TECH_STYLE_CSS);
    let app_js = String::from_utf8_lossy(TECH_APP_JS);

    let json_blob = serde_json::to_string(result)?;

    let metric_cards = build_metric_cards(result);
    let nav_buttons = build_nav_buttons(result);

    let has_cloud = !result.aws.is_empty() || !result.azure.is_empty() || !result.gcp.is_empty();
    let has_languages = !result.languages.is_empty();
    let has_deps = !result.node.is_empty()
        || !result.python.is_empty()
        || !result.go.is_empty()
        || !result.java.is_empty()
        || !result.php.is_empty()
        || !result.rust.is_empty()
        || !result.ruby.is_empty();

    let html = format!(
        r##"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>TechDetect Report</title>
<style>
{style_css}
</style>
</head>
<body>
<nav class="rg-nav">
<div class="rg-nav-brand">TechDetect</div>
<div class="rg-nav-links">
{nav_buttons}
</div>
</nav>

<div class="bg-gradient-dark">
<div class="container">

<div id="section-overview" class="report-header section-anchor">
<h1>Technology Detection Report</h1>
<p class="subtitle">Generated by RepoAnalyze &mdash; Automated Technology Stack Analysis</p>
</div>

<!-- Overview Cards -->
<div class="metric-grid">
{metric_cards}
</div>

<!-- Languages Section -->
{languages_section}

<!-- Cloud Section -->
{cloud_section}

<!-- Resource-File Matrix -->
{matrix_section}

<!-- Stack Section (Frameworks + Databases) -->
{stack_section}

<!-- Infrastructure Section -->
{infra_section}

<!-- Quality Section -->
{quality_section}

<!-- Dependencies Section -->
{deps_section}

<!-- Manifest Files -->
<div class="card">
<h2>Analyzed Manifest Files</h2>
<div id="manifest-list"></div>
</div>

</div>
</div>

<script>window.__TECH_DATA__ = {json_blob};</script>
<script src="https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js"></script>
<script>
{app_js}
</script>
</body>
</html>"##,
        style_css = style_css,
        nav_buttons = nav_buttons,
        metric_cards = metric_cards,
        json_blob = json_blob,
        app_js = app_js,
        languages_section = if has_languages {
            r#"<div id="section-languages" class="section-anchor"></div>
<div class="chart-grid">
<div class="card">
<h2>Language Distribution</h2>
<div id="language-donut-chart" class="chart"></div>
</div>
<div class="card">
<h2>Files by Language</h2>
<div id="language-bar-chart" class="chart-tall"></div>
</div>
</div>"#
        } else { "" },
        cloud_section = if has_cloud {
            r#"<div id="section-cloud" class="card section-anchor">
<h2>Cloud Services</h2>
<div id="cloud-services"></div>
</div>"#
        } else {
            r#"<div id="section-cloud" class="card section-anchor">
<h2>Cloud Services</h2>
<div class="empty-state"><div class="empty-icon">&#9729;&#65039;</div><div>No cloud services detected</div></div>
</div>"#
        },
        matrix_section = if has_cloud {
            r#"<div class="card">
<h2>Resource &times; File Matrix</h2>
<div id="resource-matrix"></div>
<div id="matrix-tooltip" class="matrix-tooltip"></div>
</div>"#
        } else { "" },
        stack_section = format!(r#"<div id="section-stack" class="section-anchor"></div>
<div class="chart-grid">
<div class="card">
<h2>Frameworks</h2>
<div id="frameworks-grid"></div>
</div>
<div class="card">
<h2>Databases</h2>
<div id="databases-grid"></div>
</div>
</div>"#),
        infra_section = format!(r#"<div id="section-infra" class="section-anchor"></div>
<div class="chart-grid">
<div class="card">
<h2>Infrastructure &amp; CI/CD</h2>
<div id="infra-grid"></div>
</div>
<div class="card">
<h2>Tool Categories</h2>
<div id="infra-donut-chart" class="chart"></div>
</div>
</div>"#),
        quality_section = format!(r#"<div id="section-quality" class="section-anchor"></div>
<div class="chart-grid">
<div class="card">
<h2>Testing &amp; Code Quality</h2>
<div id="quality-grid"></div>
</div>
<div class="card">
<h2>Quality Tool Coverage</h2>
<div id="quality-bar-chart" class="chart"></div>
</div>
</div>"#),
        deps_section = if has_deps {
            r#"<div id="section-deps" class="section-anchor"></div>
<div class="chart-grid">
<div class="card" style="grid-column: span 2">
<h2>Dependencies</h2>
<div id="deps-container"></div>
</div>
</div>
<div class="card">
<h2>Packages by Ecosystem</h2>
<div id="deps-donut-chart" class="chart"></div>
</div>"#.to_string()
        } else {
            r#"<div id="section-deps" class="card section-anchor">
<h2>Dependencies</h2>
<div class="empty-state"><div class="empty-icon">&#128230;</div><div>No package dependencies detected</div></div>
</div>"#.to_string()
        },
    );

    std::fs::write(out_path, html)?;
    Ok(())
}

fn fmt_num(n: u64) -> String {
    let s = n.to_string();
    let bytes = s.as_bytes();
    let mut result = String::new();
    for (i, &b) in bytes.iter().enumerate() {
        if i > 0 && (bytes.len() - i).is_multiple_of(3) {
            result.push(',');
        }
        result.push(b as char);
    }
    result
}

fn build_metric_cards(result: &TechDetectResult) -> String {
    let total_packages: usize = result.node.len()
        + result.python.len()
        + result.go.len()
        + result.java.len()
        + result.php.len()
        + result.rust.len()
        + result.ruby.len();

    // Count unique cloud services
    let mut unique_services: std::collections::HashSet<&str> = std::collections::HashSet::new();
    for s in &result.aws { unique_services.insert(&s.service); }
    for s in &result.azure { unique_services.insert(&s.service); }
    for s in &result.gcp { unique_services.insert(&s.service); }

    let items: Vec<(&str, u64)> = vec![
        ("Total Files", result.total_files),
        ("Manifests", result.manifest_files.len() as u64),
        ("Languages", result.languages.len() as u64),
        ("Cloud Services", unique_services.len() as u64),
        ("Frameworks", result.frameworks.len() as u64),
        ("Databases", result.databases.len() as u64),
        ("CI/CD Tools", result.cicd.len() as u64),
        ("Quality Tools", result.testing.len() as u64),
        ("Packages", total_packages as u64),
    ];

    let mut html = String::new();
    for (label, val) in items {
        html.push_str(&format!(
            "<div class=\"metric-card\"><div class=\"value\">{}</div><div class=\"label\">{}</div></div>\n",
            fmt_num(val), label
        ));
    }
    html
}

fn build_nav_buttons(result: &TechDetectResult) -> String {
    let mut buttons = Vec::new();
    buttons.push(("overview", "Overview"));
    if !result.languages.is_empty() {
        buttons.push(("languages", "Languages"));
    }
    buttons.push(("cloud", "Cloud"));
    buttons.push(("stack", "Stack"));
    buttons.push(("infra", "Infrastructure"));
    buttons.push(("quality", "Quality"));
    let total_packages: usize = result.node.len()
        + result.python.len()
        + result.go.len()
        + result.java.len()
        + result.php.len()
        + result.rust.len()
        + result.ruby.len();
    if total_packages > 0 {
        buttons.push(("deps", "Dependencies"));
    }

    buttons
        .iter()
        .map(|(id, label)| {
            format!(
                "<button data-section=\"{id}\">{label}</button>"
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}
