//! Markdown export — formatted report with sections and tables.

use crate::scoring::ScoreResult;

pub fn export_markdown(score: &ScoreResult, repo_name: &str) -> String {
    let mut out = String::new();

    // Header
    out.push_str(&format!("# Report Card: {repo_name}\n\n"));
    out.push_str(&format!(
        "**Overall Score:** {} ({})\n\n",
        score.overall_score, score.grade
    ));
    out.push_str(&format!("*Scored at: {}*\n\n", score.scored_at));

    // Category summary table
    out.push_str("## Categories\n\n");
    out.push_str("| Category | Score | Grade | Weight |\n");
    out.push_str("|----------|-------|-------|--------|\n");
    for cat in &score.categories {
        out.push_str(&format!(
            "| {} | {} | {} | {:.0}% |\n",
            cat.label,
            cat.score,
            cat.grade,
            cat.weight * 100.0
        ));
    }
    out.push('\n');

    // Detailed signals per category
    out.push_str("## Details\n\n");
    for cat in &score.categories {
        out.push_str(&format!("### {} ({} - {})\n\n", cat.label, cat.score, cat.grade));
        out.push_str("| Signal | Status | Points | Details |\n");
        out.push_str("|--------|--------|--------|---------|\n");
        for sig in &cat.signals {
            let status = if sig.found { "Pass" } else { "Fail" };
            let icon = if sig.found { "+" } else { "-" };
            out.push_str(&format!(
                "| {icon} {} | {status} | {} | {} |\n",
                sig.name, sig.points, sig.details
            ));
        }
        out.push('\n');
    }

    // Strengths
    if !score.strengths.is_empty() {
        out.push_str("## Strengths\n\n");
        for s in &score.strengths {
            out.push_str(&format!("- {s}\n"));
        }
        out.push('\n');
    }

    // Risks
    if !score.risks.is_empty() {
        out.push_str("## Risks\n\n");
        for r in &score.risks {
            out.push_str(&format!("- {r}\n"));
        }
        out.push('\n');
    }

    // Next Steps
    if !score.next_steps.is_empty() {
        out.push_str("## Next Steps\n\n");
        for ns in &score.next_steps {
            out.push_str(&format!("- {ns}\n"));
        }
        out.push('\n');
    }

    out.push_str("---\n*Generated by RepoGuru*\n");

    out
}
